apiVersion: v1
kind: Service
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: service-1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: default
  labels:
    app: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: service-1
          env:
            - name: OTEL_TRACES_EXPORTER
              value: "jaeger"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "<IP_ADDRESS>:14250"
            - name: OTEL_EXPORTER_JAEGER_SERVICE_NAME
              value: "cloud-gateway"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080