apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: service-1
build:
  artifacts:
  - image: service-1
    context: .
    jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
