apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: cloud-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  namespace: default
  labels:
    app: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
        - name: cloud-gateway
          image: cloud-gateway
          env:
            - name: OTEL_TRACES_EXPORTER
              value: "jaeger"
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "<IP_ADDRESS>:14250"
            - name: OTEL_EXPORTER_JAEGER_SERVICE_NAME
              value: "cloud-gateway"

          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080