apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cloud-gateway
build:
  artifacts:
  - image: cloud-gateway
    context: .
    jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
